app/models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash

db = SQLAlchemy()

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String, nullable=False)
    last_name = db.Column(db.String, nullable=False)
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    created_on = db.Column(db.DateTime, default=datetime.utcnow())

    def __init__(self, firstName, lastName, email, password):
        self.first_name = firstName
        self.last_name = lastName
        self.email = email
        self.password = generate_password_hash(password)

app/__init__.py
from flask import Flask
from config import Config
from flask_login import LoginManager
from app.models import db, User
from flask_migrate import Migrate


app = Flask(__name__)
app.config.from_object(Config)

login_manager = LoginManager()

login_manager.init_app(app)
db.init_app(app)
migrate = Migrate(app,db)

#login_manager settings
login_manager.login_view= 'auth.login'
login_manager.login_message ='You must log in to view this page'
login_manager.login_message_category ='warning'


#importing blueprints
from app.blueprints.auth import auth
from app.blueprints.poke import poke

# registering blueprints
app.register_blueprint(auth)
app.register_blueprint(poke)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/blueprints/poke/__init__.py
from flask import Blueprint

poke = Blueprint('poke', __name__, template_folder='poketemplates')
from . import routes
    

app/blueprints/poke/routes.py
from app.blueprints.poke import poke
from flask import request, render_template
from flask_login import login_required
import requests

@poke.route('/')
@poke.route('/home')
def homePage():
    return render_template('home.html')

@poke.route('/pokeForm', methods=['GET','POST'])
@login_required
def poke_form():
    form = poke_form()
    if request.method =='POST':
        poke_data = form.name.data
        try:
            print(poke_data)
            poke_url= f"https://pokeapi.co/api/v2/pokemon/{poke_data}"
            response = requests.get(poke_url)
            poke_stats = response.json()
            poke_dict = {
                'name' : poke_stats['forms'][0]['name'],
                'ability_name' :poke_stats['abilities'][1]['ability']['name'],
                'base_experience' :poke_stats['base_experience'],
                'attack_base_stat' :poke_stats['stats'][1]['base_stat'],
                'defense_base_stat' :poke_stats['stats'][2]['base_stat'],
                'hp_base_stat' :poke_stats['stats'][0]['base_stat'],
                'sprites_image':poke_stats['sprites']['front_shiny']
            }
           
            return render_template('pokeForm.html', pokemon_info=poke_dict, form=form)
        except:
            return render_template('pokeForm.html',form=form)
    else:
        return render_template('pokeForm.html', form=form)
    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:opsz,wght@6..12,300&family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    {% block styles %} {% endblock %}
    <title>{%block title %} {%endblock%}</title>
</head>
<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category,message in messages %}
            <div class="m-0 p-0 alert alert-{{category}} alert-dismissible fade show" role="alert">
                <p>{{ message }}</p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {% block content%}
    
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html> 

app/templates/includes/nav.html
<nav  class ="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Pokemon</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text mr-2">{{ current_user.firstName }}</span>
                    <a class="btn btn-danger" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{{url_for('poke.homePage')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('poke.poke_form')}}"> Create Your Team</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.signup')}}">Create An Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.login')}}">Returning Users</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

app/templates/login.html
{% extends 'base.html'%}

{% block styles %}
<link rel="stylesheet" href="../static/styles/login.css">
{% endblock %}

{% block content %}
{% include './includes/nav.html' %}
<img class="mx-auto d-block poke-logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/International_Pok%C3%A9mon_logo.svg/2560px-International_Pok%C3%A9mon_logo.svg.png" alt="pokemon logo">
<h1 class="text-center"> Login </h1>
<form method="POST" class="w-25 mx-auto d-block shadow-lg p-3 mb-5 bg-body-tertiary rounded">
    {{ form.hidden_tag() }}
    <div class="mb-3">
      <label for="email" class="form-label">Email address</label>
      {{ form.email(class="form-control email-input", id="email")}}
      <div id="emailHelp" class="form-text "></div>
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      {{ form.password(class="form-control password-input", id="password")}}
    </div>
    {{ form.submitButton (class="login-btn btn-primary")}}
  </form>


{% endblock %}